### ISSUE TITLE
Ad compatibility problem with devices

### ISSUE THREAD

**Issue by AdamT-hub** [poingstudios/godot-admob-android#219]
### Godot version

3.5.2 stable

### Plugin version

3.4

### Phone information

Xiaomi 13C

### Issue description

I am having problems with running test ads on my Xiaomi 13c (running the example scene). You see, I did all the steps correctly but when I tested it on my Samsung Galaxy A32 it worked but on my Xiaomi it didn't. Should I check something before I export it to support other devices? Or is this just a bug.

### Steps to reproduce

1. Do all the steps correctly to make the Godot admob ads work.
2. Export it with Android
3. Test the example scene on a Xiaomi phone

**Comment by gumaciel** [comment]
Hi, did you try to export the game without our plugin to see if it works on your phone?

Check this video to debug with `adb` and check if some errors show to you: https://youtu.be/0NxYJgATevg?t=1970

**Comment by AdamT-hub** [comment]
Yes I did already export it without the plugin and it worked

**Comment by AdamT-hub** [comment]
> Hi, did you try to export the game without our plugin to see if it works on your phone?
> 
> Check this video to debug with `adb` and check if some errors show to you: https://youtu.be/0NxYJgATevg?t=1970

**Comment by gumaciel** [comment]
Can you try to provide more information with `adb`, with the video that I mentioned before? It's hard to know the issue without it

**Comment by AdamT-hub** [comment]
You see I have watched that video before and did all the steps, what is strange is how the ads are not compatible with Xiaomi. Because if it's working on Samsung, it should work on Xiaomi (please do note that I'm using Godot 3.5.2 and the admob plugin of that version so I don't know if there was a bug like this at the time of the plugin). If you want to test it for yourself just get a Xiaomi phone at the same version of Godot and export it with the plugin.

**Comment by gumaciel** [comment]
Yeah, it should work on Xiaomi.

The reason for not working on your phone normally can be the processor which is not supported, the phone model may not interfere with the operation.

I will try to test here, but please try to prove us more information with `adb`, it will be much more easier to track the problem and solve this issue

**Comment by gumaciel** [comment]
Hey, @AdamT-hub can you provide us more information with `adb`? We couldn't reproduce this issue from our site.
https://developer.android.com/tools/adb

You can try to use these two commands:

`adb logcat -s poing-godot-admob`
`adb logcat -s godot`

or any other which can show us the an exception which cause this crash, thank you very much

**Comment by gumaciel** [comment]
hey @AdamT-hub this issue still happen? if so, please try to provide us with more information with `adb`

**Comment by AdamT-hub** [comment]
Hello, gumaciel. I'm very sorry for not responding earlier. I think the problem was some settings on my phone (I am now using Godot 4's admob plugin). Thank you very much for your help and dedication to this plugin.

> hey @AdamT-hub this issue still happen? if so, please try to provide us with more information with `adb`
