### ISSUE TITLE
Families Policy Requirements

### ISSUE THREAD

**Issue by Severus0325** [poingstudios/godot-admob-android#223]
### Godot version

3.5.3

### Plugin version

v2.1.5

### Phone information

android 13

### Issue description

Hello, thank you for the Admob module. I make games for children. I am troubled by the following email from google.

About Families Policy Requirements
Apps that solely target children must not transmit the following:
Android Advertising ID (AAID)
SIM Serial
Build Serial
BSSID
MAC
SSID
IMEI and/or IMSI

Apps that target both children and older audiences must not transmit the listed identifiers from children or users of unknown age.

I think the solution is to block device identifiers Android Advertising ID (AAID), SIM Serial, Create Serial, BSSID, MAC, SSID, IMEI ,IMSI.I tried the solution in issue #164, but I still get the warning email from Google. Can I prevent the Admob module from getting these permissions?

### Steps to reproduce

Include ages 13 and under in app's target age range in Google Play Console

**Comment by gumaciel** [comment]
Hi, you probably need to implement a neutral age screen, please check this: https://support.google.com/googleplay/android-developer/thread/242178712/apps-that-solely-target-children-should-not-transmit-aaid?hl=en

https://support.google.com/admob/thread/78044598/can-i-simply-ask-age-on-neutral-age-screen?hl=en

**Comment by Severus0325** [comment]
Thank you for your comment.
I'll try adding age verification to my app so that I can only send data for adults.
