### ISSUE TITLE
TOP Banner Ad position is leaving a wide gap

### ISSUE THREAD

**Issue by lazyvainglory** [poingstudios/godot-admob-android#226]
### Godot version

4.2.2

### Plugin version

v3.0.3

### Phone information

Poco & AVD both with Android 13

### Issue description

When positioning a banner ad at the top (AdSize.BANNER and AdPosition.Values.TOP), the ad leaves a gap equal to its height. This behavior is also observed in the provided sample scene.

![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/921d11f7-b3b5-4f0c-ab96-bdc786434c76)

This issue, however, does not occur in your tutorial video. So, I believe this is a bug.

![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/ee64a0f2-1056-4b2a-88f3-aad52b1e12b5)

### Steps to reproduce

Run the sample scene and load a top banner ad.

**Comment by gumaciel** [comment]
Hi @lazyvainglory did you modify your `AndroidManifest.xml` or some file to change your SafeArea?

What is your phone? Poco X3?

**Comment by lazyvainglory** [comment]
My Phone is POCO X3 Pro. The only thing I changed/ added in the manifest was the one in the instructions.

```
<!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
<meta-data
	android:name="com.google.android.gms.ads.APPLICATION_ID"
	android:value="ca-app-pub-3940256099942544~3347511713"/>
```
The sample project also has problems, and I didn’t even change anything there.

![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/4dc6cb69-b155-4956-a5af-acca99782801)

**Comment by gumaciel** [comment]
@lazyvainglory please try with this `.zip`: [poing-godot-admob-android-v4.2.1.zip](https://github.com/poingstudios/godot-admob-android/files/15505213/poing-godot-admob-android-v4.2.1.zip)

was built in 4.2.1 but also works in 4.2.2

**Comment by lazyvainglory** [comment]
@gumaciel Thank you so much.

**Comment by gumaciel** [comment]
@lazyvainglory you're welcome, please let me know if these binaries will work for you

**Comment by lazyvainglory** [comment]
@gumaciel It is still a problem. Interstitial is fine though so I'll just stick to it. 
![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/8a74d587-f4be-4257-9e09-687954dd531c)

**Comment by gumaciel** [comment]
This gap is not about the "notch" of the phone?

![Screenshot_2024-05-31-06-39-00-725_org.godotengine.admobaddon-edit.jpg](https://github.com/poingstudios/godot-admob-android/assets/20030153/5ac29306-4dca-46eb-8d71-9f153616a9bd)

Mine is like this

**Comment by lazyvainglory** [comment]
Good thing you mentioned the notch. In order to avoid dealing with the notch, I actually disable ‘Immersive Mode’ in the export settings. So this is probably why you are not experiencing this issue. I also build the project with ‘Immersive Mode’ enabled, and the plug-in is fine. Sorry for not realizing this before.

![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/d2604466-0fda-46db-90e6-669981aa9829)
![image](https://github.com/poingstudios/godot-admob-android/assets/45304248/a13fa1de-0bbf-4d5e-acda-cc5323c17a92)

**Comment by gumaciel** [comment]
@lazyvainglory thank you for this information, I can confirm this bug and working on a fix right now

**Comment by gumaciel** [comment]
@lazyvainglory fixed on https://github.com/poingstudios/godot-admob-android/releases/tag/v3.0.4

Please test it
