### ISSUE TITLE
Action required: Migrate to a supported version of the Google Play Billing Library

### ISSUE THREAD

**Issue by Shay-M** [poingstudios/godot-admob-android#227]
### Godot version

4.2.1

### Plugin version

v3.1.1

### Phone information

android 12

### Issue description

Hi, first of all, thanks for the plugin, I don't know where to write it because it's not really a bug. In the Google store under development, this message popped up:

Action required: Migrate to a supported version of the Google Play Billing Library

We are introducing changes to the lifecycle of the Play Billing Library and its associated deprecation timelines. Because you currently use an older version of the library, we wanted you to be aware of new key dates that you'll need to adhere to:

By 31 August 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer. If you need more time to update your app, you will be able to request an extension until 1 November 2024.

Is this something that needs to be updated independently?

### Steps to reproduce

The message pops up in the Google store
![image](https://github.com/poingstudios/godot-admob-android/assets/22634623/74b13569-b044-4bdb-b71a-4961ae0cb10a)

**Comment by gumaciel** [comment]
Hi @Shay-M , this message is about Google Play Billing Library, not AdMob, in this plugin, we do not use this library.

Probably you have another plugin for billing, I suggest you open the issue in the repository of this plugin.

**Comment by Shay-M** [comment]
Oh right, you're right. Thank you!
