### ISSUE TITLE
PoingGodotAdMob not found

### ISSUE THREAD

**Issue by PerfectlyFineCode** [poingstudios/godot-admob-android#228]
### Godot version

4.2.2

### Plugin version

3.1.1

### Phone information

Samsung Galaxy S20 Ultra - Android 13

### Issue description

`adb logcat -s godot` produces this log
```
06-18 10:36:09.310 13472 13539 E godot   : PoingGodotAdMob not found, make sure you marked all 'PoingAdMob' plugins on export tab
06-18 10:36:09.313 13472 13539 E godot   : PoingGodotAdMobAdSize not found, make sure you marked all 'PoingAdMob' plugins on export tab
06-18 10:36:09.342 13472 13539 E godot   : PoingGodotAdMobAdView not found, make sure you marked all 'PoingAdMob' plugins on export tab
```
I see no options to mark anything in export tab.

### Steps to reproduce

1. Install
2. Set up
3. Debug on Android
4. Attach logcat

### Additional context

```gdscript
extends Node
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	MobileAds.initialize()
	var unit_id: String
	if OS.get_name() == "Android":
		unit_id = "ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxx"

	var ad_view := AdView.new(unit_id, AdSize.BANNER, AdPosition.Values.TOP)
	ad_view.load_ad(AdRequest.new())
```

**Comment by lironxyz** [comment]
I'm also having this issue after adding `minifyEnabled true` to `build.gradle` file in order to invoke minification (proguard).
@PerfectlyFineCode are you having this issue due to minification as well?

**Comment by gumaciel** [comment]
@PerfectlyFineCode you probably missed to put the files in place correctly, so Godot can't find the plugin for Android.

When you export, it needs to be like this, if is not, then it's wrong.
![Screenshot 2024-09-01 at 23 47 41](https://github.com/user-attachments/assets/e6b982b6-c6ba-49d2-bd98-05b1e081b87f)

**Comment by gumaciel** [comment]
@lironxyz I tried to use `minify Enabled true` but my Sample App crashes even with `Ad Mob` plugin disabled:

```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.NoSuchMethodError: no non-static method "Lorg/godotengine/godot/Godot;.restart()V"
```
