### ISSUE TITLE
PoingGodotAdMobAdColonyAppOptions not found

### ISSUE THREAD

**Issue by Shay-M** [poingstudios/godot-admob-android#231]
### Godot version

4.2.1

### Plugin version

v3.1.1

### Phone information

android 12

### Issue description

Hello everyone, thanks for this plugin.
I have this strange problem:

```
PoingGodotAdMobVungle not found, make sure you marked all 'PoingAdMob' plugins on export tab
_on_consent_info_updated_success
MobileAds initialization complete
Key: com.google.android.gms.ads.MobileAds Latency: 1677 Initialization Status: 1 Description: 
Key: com.google.ads.mediation.vungle.VungleMediationAdapter Latency: 2 Initialization Status: 0 Description: Failed to create Adapter.
Key: com.google.ads.mediation.applovin.AppLovinMediationAdapter Latency: 3 Initialization Status: 0 Description: Failed to create Adapter.
Key: com.google.ads.mediation.adcolony.AdColonyMediationAdapter Latency: 4 Initialization Status: 0 Description: Failed to create Adapter.
Key: com.google.ads.mediation.tapjoy.TapjoyMediationAdapter Latency: 3 Initialization Status: 0 Description: Failed to create Adapter.
  PoingGodotAdMobAdColonyAppOptions not found, make sure you marked all 'PoingAdMob' plugins on export tab
set values ad_colony

false

false
```

but i marke it:
![image](https://github.com/poingstudios/godot-admob-android/assets/22634623/36660f20-c429-4b9b-ae9c-663cea4e0e84)
![image](https://github.com/poingstudios/godot-admob-android/assets/22634623/c469eb2d-3d46-4e61-bcb9-36358e0e1c93)
In addition, I also opened Internet permissions

### Steps to reproduce

I tried twice according to the video 
https://www.youtube.com/watch?v=WpVGn7ZasKM

**Comment by gumaciel** [comment]
Hi, that's normal if you don't put the `Ad Colony` plugin to export like this:
![Screenshot 2024-09-01 at 23 40 59](https://github.com/user-attachments/assets/e41eddbf-4fee-4dfc-aa39-0718eb37c2b7)


Remember that if you want to use this mediation, you need to put the files on `res://android/plugins` folder
![Screenshot 2024-09-01 at 23 41 30](https://github.com/user-attachments/assets/81a592a1-1e82-4649-92dd-c72015fade44)

**Comment by HaleyHalcyon** [comment]
Oh, so I have to take the contents OUT of the /ads/ folder and put them in `res://android/plugins/.` I see, the guide wasn't very clear on that point.
