### ISSUE TITLE
LTS for Godot 3.x til Godot 4 is mature

### ISSUE THREAD

**Issue by kyoz** [poingstudios/godot-admob-android#234]
### What feature or improvement would you like to see?

Google is getting stricter every day, so updating apps should usually be unavoidable.

![image](https://github.com/user-attachments/assets/bdf10ba8-87ff-48a9-ac7c-c62ede06b39a)

Since lot's of developers still stick with Godot 3, although we have to move to Godot 4, there's no way back. But have a little more support to let em upgrade their apps to Godot 4 is nice. Of course with limited support.

On Android, it's pretty easy, i've tried to build a version with ads 23.0.0 and it'll able to work to Q1-2026

![Screenshot 2024-07-17 at 15 33 17](https://github.com/user-attachments/assets/3f1594a5-d947-4771-acc0-a87922d33a79)

On iOS, with your latest v2 release, using MobileAds version 10.13.0 (which is support to Q1 2025). I don't know the dependencies so haven't tried, but it would be nice if it can upgrade to v11. I can no longer found the dev workflow on the wiki of your repos :'(

![Screenshot 2024-07-17 at 15 45 14](https://github.com/user-attachments/assets/c9742208-86cb-4e63-905f-697223a33539)

Then we will have v2 plugin for both Android & iOS that support to 2016, and i think that's fine and no need to touch it anymore cause new features will go all for Godot 4.

How do you think @gumaciel?

**Comment by Molly-Rose-Pastel** [comment]
I have a lot of games made with godot 3.x and I don't see myself porting them to 4.x anytime soon, if at all. 
There is a reason godot 3.x has LTS so it would be really nice if this plugin did the same

**Comment by gumaciel** [comment]
Hello y'all, I agree with all of you, in about one month I will try to update the plugins for Android and iOS.

If possible and anyone who knows about Android/iOS plugins, I would appreciate very much if someone help me, because now I have a lot of things to do.

Until this, please wait for the update.

**Comment by kyoz** [comment]
Yeah sure @gumaciel , as i told, v2 doesn't need any new features. Just support it as it is, that'll be enough. For Android, i've created a PR, you can test it and release a version for it.

I still stuck with iOS development cause the wiki are all gone, will try it later on.

**Comment by gumaciel** [comment]
Done, thank you!

Reminder: You need to set the Min Sdk to 21
![Screenshot 2024-09-02 at 21 53 12](https://github.com/user-attachments/assets/82f91778-a8d2-4fd2-934a-eb045d509636)
