### ISSUE TITLE
Ads won't load/work on samples or anything else

### ISSUE THREAD

**Issue by KitKatTheCat** [poingstudios/godot-admob-android#236]
### Godot version

4.2.2

### Plugin version

3.1.1

### Phone information

TECHNO POVA 4 Android 12

### Issue description

I have done everything did the guide said, I added my app id, enabled admob plugin and the export as well. I enabled Internet, Access Network State and Access Wifi State. And it the ads won't show even the sample ones

### Steps to reproduce

1. I just exported the game normally

**Comment by powerlsj7** [comment]
안녕하세요? 저도 똑같은 증상이 있습니다! 4.2.2에서는 작동하지 않는건가요? plugins폴더를 만들고 lib파일도 이동시켰지만 에디터나 빌드후 안드로이드에서도 똑같이 무반응입니다.

**Comment by gumaciel** [comment]
I think this is due wrong plugin configuration, join our discord and we can help you: https://discord.com/invite/YEPvYjSSMk

**Comment by gumaciel** [comment]
@KitKatTheCat is still happening?

**Comment by KitKatTheCat** [comment]
I think the fix was waiting for your admob account to be recognized or something...
